In [19]:
import numpy as np

arr = np.array([3, 5, 2, 5, 6, 9, 8])

***Sorting***

In [20]:
# implace
sorted_arr = arr.copy()
sorted_arr.sort()

print(f"Sorted Array: {sorted_arr}")

Sorted Array: [2 3 5 5 6 8 9]


In [21]:
# copy sort
sorted_arr = np.sort(arr)

print(f"Sorted Array: {sorted_arr}")

Sorted Array: [2 3 5 5 6 8 9]


***2D Array Sorting***

In [22]:
matrix = np.array([
    [2, 4, 9, 5, 8], 
    [5, 3, 2, 8, 7]])

# horizontal axis = 1
hor_sort = np.sort(matrix, axis=1)
print(f"Sorted Array (Horizontally):\n{hor_sort}")

print('\n')

# vertical axis = 0
hor_sort = np.sort(matrix, axis=0)
print(f"Sorted Array (Vertically):\n{hor_sort}")

Sorted Array (Horizontally):
[[2 4 5 8 9]
 [2 3 5 7 8]]


Sorted Array (Vertically):
[[2 3 2 5 7]
 [5 4 9 8 8]]


***Searching***

In [23]:
# np.where(condition, x, y) if true x, else replace with y
index = np.where(arr > 5)
print(index)

index = np.where(arr > 5, arr, 0) # returns array
print(index)

(array([4, 5, 6]),)
[0 0 0 0 6 9 8]


***2D Array***

In [24]:
index = np.where(matrix > 5)
print(index)

index = np.where(matrix > 5, matrix, 0)
print(index)

(array([0, 0, 1, 1]), array([2, 4, 3, 4]))
[[0 0 9 0 8]
 [0 0 0 8 7]]


In [25]:
# maximum value
maximim_value_index = np.argmax(arr)
print(f"Maximim Value Index: {maximim_value_index}")

# minimum value
minimum_value_index = np.argmin(arr)
print(f"Minimum Value Index: { minimum_value_index}")

Maximim Value Index: 5
Minimum Value Index: 2


***2D Array***

In [26]:
# maximum value
maximim_value_index = tuple(map(int, np.unravel_index(np.argmax(matrix), matrix.shape)))
print(f"Maximim Value Index: {maximim_value_index}")

# minimum value
minimum_value_index = tuple(map(int, np.unravel_index(np.argmin(matrix), matrix.shape)))
print(f"Minimum Value Index: { minimum_value_index}")

Maximim Value Index: (0, 2)
Minimum Value Index: (0, 0)


***Counting***

In [27]:
arr = np.random.randint(1, 100, size=100)
print(f"Array: {arr}")

x = np.count_nonzero(arr > 60)
print(f"Value Greater than 60: {x}")

Array: [16  5 55 45 73 78 65 61  4 24 48 78 17  6 92 77 43 26 12 51 20 63 48 28
 86 96 34 85 89 62  8 22 77 31 59  3  4 31 73 32 66 45 32 32 93 64 63 99
 90 52 44 41  9 48 11 85 74 97 25 41 79 89 37 64 62 44 54 75 10 88 42 27
 55 89 95 32 63 77  6 18 39 93 22 43 81 78 22 19 31 72 26 80 84 61 80  3
 21 76 48 57]
Value Greater than 60: 43


***Unique Value***

In [28]:
# unique value
arr = np.random.randint(1, 10, size=10)
print(f"Array: {arr}")

unique_value = np.unique(arr)
print(f"Unique Value: {unique_value}")


unique_value = np.unique(arr, return_counts=True)
print(f"Unique Values with Mapping: {unique_value}")

Array: [2 6 3 5 5 4 3 2 9 9]
Unique Value: [2 3 4 5 6 9]
Unique Values with Mapping: (array([2, 3, 4, 5, 6, 9], dtype=int32), array([2, 2, 1, 2, 1, 2]))
