***Data Load***

In [28]:
import numpy as np

data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=True)
# column 1 -> Math marks, column 2 -> Science marks, column 3 -> English marks
print(f"Data Set:\n{data}") 

Data Set:
[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


***Math***

In [29]:
math_marks = data[ :: , :1]
print(f"Math Marks: {math_marks.T}")

# maximum number
max_math_marks = np.max(math_marks)
print(f"Maximum Math Marks: {max_math_marks}")

# minimum number
min_math_marks = np.min(math_marks)
print(f"Minimum Math Marks: {min_math_marks}")

# average
avg_math_marks = np.mean(math_marks)
print(f"Average Math Marks: {avg_math_marks}")

# meadian
median_math_marks = np.median(math_marks)
print(f"Median Math Marks: {median_math_marks}")

# standard deviation
std_math_marks = np.std(math_marks)
print(f"Standard Deviation: {std_math_marks}")


Math Marks: [[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
Maximum Math Marks: 95.0
Minimum Math Marks: 45.0
Average Math Marks: 73.15
Median Math Marks: 73.5
Standard Deviation: 13.788672887555204


***Science***

In [30]:
science_marks = data[ :: , 1:2]
print(f"Science Marks: {science_marks.T}")

# maximum number
max_science_marks = np.max(science_marks)
print(f"Maximum Science Marks: {max_science_marks}")

# minimum number
min_science_marks = np.min(science_marks)
print(f"Minimum Science Marks: {min_science_marks}")

# average
avg_science_marks = np.mean(science_marks)
print(f"Average Science Marks: {avg_science_marks}")

# meadian
median_science_marks = np.median(science_marks)
print(f"Median Science Marks: {median_science_marks}")

# standard deviation
std_science_marks = np.std(science_marks)
print(f"Standard Deviation: {std_science_marks}")


Science Marks: [[85. 67. 92. 52. 75. 90. 60. 57. 89. 70. 69. 82. 64. 78. 93. 71. 79. 86.
  63. 97.]]
Maximum Science Marks: 97.0
Minimum Science Marks: 52.0
Average Science Marks: 75.95
Median Science Marks: 76.5
Standard Deviation: 12.804198530169703


***English***

In [31]:
english_marks = data[ :: , 2:3]
print(f"English Marks: {english_marks.T}")

# maximum number
max_english_marks = np.max(english_marks)
print(f"Maximum English Marks: {max_english_marks}")

# minimum number
min_english_marks = np.min(english_marks)
print(f"Minimum English Marks: {min_english_marks}")

# average
avg_english_marks = np.mean(english_marks)
print(f"Average English Marks: {avg_english_marks}")

# meadian
median_english_marks = np.median(english_marks)
print(f"Median English Marks: {median_english_marks}")

# standard deviation
std_english_marks = np.std(english_marks)
print(f"Standard Deviation: {std_english_marks}")


English Marks: [[82. 72. 88. 58. 80. 91. 62. 54. 87. 76. 68. 81. 60. 74. 90. 69. 78. 85.
  65. 96.]]
Maximum English Marks: 96.0
Minimum English Marks: 54.0
Average English Marks: 75.8
Median English Marks: 77.0
Standard Deviation: 11.749893616539683


***Correlation Coefficient***

In [32]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_score = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_score])

correlation = np.corrcoef(data)
print(f"Correlation Matrix:\n{correlation}")

Correlation Matrix:
[[1.         0.99859154]
 [0.99859154 1.        ]]
