In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [95]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta
        self.epochs = epochs

        print(f"Self.Weights: {self.weights}")

    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z > 0 , 1, 0)

    def fit(self, x, y):
        self.x = x
        self.y = y

        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"X with Bias: {x_with_bias}")

        for epoch in range(self.epochs):
            print(f"Epoch: {epoch}")

            
            y_hat = self.activationFunction(x_with_bias, self.weights) # prediction
            error = self.y - y_hat # error
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, error) # weight update

            print(f"Predicted Result: {y_hat}")
            print(f"Error: \n{error}")
            print(f"Updated Weights: {self.weights}")
            print("--------------")

    def predict(self, x):
        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]

        return self.activationFunction(x_with_bias, self.weights)


# AND Gate

In [96]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 0, 0, 1]
}

AND = pd.DataFrame(data) 

x = AND.drop('y', axis=1)
y = AND['y']
y.to_frame()

,y
0,0
1,0
2,0
3,1


***Model Prediction***

In [97]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(x,y)

Self.Weights: [1.56018640e-05 1.55994520e-05 5.80836122e-06]
X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted Result: [0 1 1 1]
Error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-0.4999844  -0.4999844   1.00000581]
--------------
Epoch: 1
Predicted Result: [0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [1.56018640e-05 1.55994520e-05 5.00005808e-01]
--------------
Epoch: 2
Predicted Result: [0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [5.00015602e-01 5.00015599e-01 5.80836122e-06]
--------------
Epoch: 3
Predicted Result: [0 1 1 1]
Error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [1.56018640e-05 1.55994520e-05 1.00000581e+00]
--------------
Epoch: 4
Predicted Result: [0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [0.5000156  0.5000156  0.50000581]
--------------
Epoch: 5
Predict

# OR Gate

In [98]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 1, 1, 1]
}

OR = pd.DataFrame(data) 

x = OR.drop('y', axis=1)
y = OR['y']
y.to_frame()

,y
0,0
1,1
2,1
3,1


***Model Prediction***

In [99]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(x,y)

Self.Weights: [8.66176146e-05 6.01115012e-05 7.08072578e-05]
X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted Result: [0 0 1 1]
Error: 
0    0
1    1
2    0
3    0
Name: y, dtype: int64
Updated Weights: [ 8.66176146e-05  5.00060112e-01 -4.99929193e-01]
--------------
Epoch: 1
Predicted Result: [1 1 1 1]
Error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 2
Predicted Result: [0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 3
Predicted Result: [0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 4
Predicted Result: [0 1 1 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
-------

# XOR Gate 

**XOR gate couldn't solve**

In [110]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 1, 1, 0]
}

XOR = pd.DataFrame(data) 

x = XOR.drop('y', axis=1)
y = XOR['y']
y.to_frame()

,y
0,0
1,1
2,1
3,0


***Model Prediction***

In [109]:
model = Perceptron(eta=0.5, epochs=10000)
model.fit(x,y)

Self.Weights: [8.66176146e-05 6.01115012e-05 7.08072578e-05]
X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted Result: [0 0 1 1]
Error: 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-4.99913382e-01  6.01115012e-05  5.00070807e-01]
--------------
Epoch: 1
Predicted Result: [0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 2
Predicted Result: [0 1 1 1]
Error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-4.99913382e-01  6.01115012e-05  1.00007081e+00]
--------------
Epoch: 3
Predicted Result: [0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 4
Predicted Result: [0 0 0 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
----

In [102]:
w = np.array([2, 2])
x = np.array([2, 2])

***Dot Product***

In [103]:
dot = np.dot(w, x) 
print(f"Weighted Sum: {dot}")

Weighted Sum: 8


***Normal Distribution***

In [104]:
random = np.random.seed(42)

In [105]:
random_normal = np.random.randn(3)
print(f"Random Values: {random_normal}")

Random Values: [ 0.49671415 -0.1382643   0.64768854]


***Concatenation***

In [106]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 0, 0, 1]
}

AND = pd.DataFrame(data) 
AND

,x1,x2,y
0,0,0,0
1,0,1,0
2,1,0,0
3,1,1,1


In [107]:
x = AND.drop('y', axis=1)
y = AND['y']
y.to_frame()
bias = np.c_[x, -np.ones((len(x), 1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])